# Form implementation generated from reading ui file 'ui/browser.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.item_browser = QtWidgets.QTableWidget(self.centralwidget)
        self.item_browser.setGeometry(QtCore.QRect(0, 32, 1000, 768))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_browser.sizePolicy().hasHeightForWidth())
        self.item_browser.setSizePolicy(sizePolicy)
        self.item_browser.setObjectName("item_browser")
        self.item_browser.setColumnCount(0)
        self.item_browser.setRowCount(0)
        self.item_browser.verticalHeader().setVisible(False)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1000, 30))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(8, 8, 64, 16))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setEnabled(True)
        self.comboBox.setGeometry(QtCore.QRect(530, 5, 128, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.name = QtWidgets.QLineEdit(self.frame)
        self.name.setGeometry(QtCore.QRect(90, 9, 128, 16))
        self.name.setObjectName("name")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(230, 8, 96, 16))
        self.label_2.setObjectName("label_2")
        self.price = QtWidgets.QLineEdit(self.frame)
        self.price.setGeometry(QtCore.QRect(320, 9, 128, 16))
        self.price.setReadOnly(False)
        self.price.setObjectName("price")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(470, 8, 64, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(909, 6, 75, 20))
        self.pushButton.setObjectName("pushButton")
        self.loading = QtWidgets.QLabel(self.frame)
        self.loading.setEnabled(True)
        self.loading.setGeometry(QtCore.QRect(690, 8, 192, 16))
        self.loading.setObjectName("loading")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.name, self.price)
        MainWindow.setTabOrder(self.price, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.item_browser)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skyblock Auction Browser"))
        self.label.setText(_translate("MainWindow", "Item Name:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Highest Price"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Lowest Price"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Ending Soon"))
        self.label_2.setText(_translate("MainWindow", "Maximum Cost:"))
        self.label_3.setText(_translate("MainWindow", "Sort by:"))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.loading.setText(_translate("MainWindow", "Index 0 of 0 items..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
